@startuml Redis POC

interface IKeyValueStorage {
    +put(const std::string& key, const std::string& value) : void
    +get(const std::string& key) : std::optional<std::string>
    +remove(const std::string& key) : void
    +print() : void
}

interface ICache {
    +isKeyInCache(const std::string& key) : bool
    +isCacheFull() : bool
    +getEvictionCandidate() : std::optional<KeyValuePair>
}

note right of ICache
using KeyValuePair =
    std::pair<std::string, std::string>
end note

class Entry <<struct>> {
    +value : std::optional<std::string>
    +lruIt : std::list<std::string>::iterator
}

class RamCache {
    -updateEvictionCandidate(std::unordered_map<std::string, Entry>::iterator it, const bool isInserted) : void
}

class SpeedbFlashStorage {
}

interface IEvictionPolicy {
    +getEvictionCandidate() : std::optional<std::string>
    +remove(std::unordered_map<std::string, Entry>::iterator it) : void
    +void updateEvictionCandidate(std::unordered_map<std::string, Entry>::iterator it, const bool isInserted) : void
    +void print() const : void
}

class LruEvictionPolicy {
}

LruEvictionPolicy -u..|> IEvictionPolicy
LfuEvictionPolicy -u..|> IEvictionPolicy


ICache -u--|> IKeyValueStorage
SpeedbFlashStorage -u..|> IKeyValueStorage
RamCache -u..|> ICache
RamCache --> "1" IEvictionPolicy

@enduml